version: '3'

services:
  php-apache:
    build:
      context: .
      dockerfile: C:\xampp\htdocs\inf653midtermproject\PHP-Docker\Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html